name: Deploy Portfolio Website

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

permissions:
  contents: write  # Allows GitHub Actions to push to the repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # This is fine since index.html is in the root
        publish_branch: gh-pages  # Where the site will be deployed
